In [1]:
import torch

In [3]:
a = torch.tensor(list(range(9)))

In [4]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

In [6]:
b = a.view(3, 3)

In [7]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
id(a.storage()) == id(b.storage())

False

In [15]:
b[1, 1] = 4

In [16]:
a,b

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [17]:
c = b[1:, 1:] # 去掉第 0 行第0 列

In [18]:
c

tensor([[4, 5],
        [7, 8]])

In [19]:
c.storage_offset()

4

In [20]:
c.stride()

(3, 1)

In [21]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [22]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])