In [1]:
import torch

In [5]:
double_points = torch.ones(10, 2, dtype=torch.double) # 10行 2 列

short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [11]:
double_points = torch.zeros(10, 2).double()
short_points = torch.zeros(5,2).short()
short_points

double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.zeros(5,2).to(dtype=torch.short)
short_points

# 两种方式等价

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

In [17]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
print(points_short) # 浮点数转为整数不会四舍五入 而是直接取整数部分全为 0
print(points_64)

tensor([0, 0, 0, 0, 0], dtype=torch.int16)
tensor([0.1518, 0.0495, 0.9579, 0.3139, 0.1086], dtype=torch.float64)


In [18]:
points_64 * points_short # 对应元素相乘 内积

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)