In [1]:
import torch

In [2]:
points = torch.zeros(4,2)
points


tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
torch.save(points, '/Users/zcq30/Documents/XJLTU Learning/XJTLU/FMP/Pytorch/DeepLearningWithPytorch/Code/p1ch3zero4_2.t')

In [5]:
with open('/Users/zcq30/Documents/XJLTU Learning/XJTLU/FMP/Pytorch/DeepLearningWithPytorch/Code/p1ch3zero4_2.t', 'wb') as f:
    torch.save(points, f)

In [7]:
a = torch.load("/Users/zcq30/Documents/XJLTU Learning/XJTLU/FMP/Pytorch/DeepLearningWithPytorch/Code/p1ch3zero4_2.t")
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
with open('/Users/zcq30/Documents/XJLTU Learning/XJTLU/FMP/Pytorch/DeepLearningWithPytorch/Code/p1ch3zero4_2.t', 'rb') as f:
    a = torch.load(f)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
import h5py

In [16]:
f = h5py.File('/Users/zcq30/Documents/XJLTU Learning/XJTLU/FMP/Pytorch/DeepLearningWithPytorch/Code/p1ch3zero4_2hdf5.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close
# 写

<bound method File.close of <HDF5 file "p1ch3zero4_2hdf5.hdf5" (mode r+)>>

In [17]:
f = h5py.File('/Users/zcq30/Documents/XJLTU Learning/XJTLU/FMP/Pytorch/DeepLearningWithPytorch/Code/p1ch3zero4_2hdf5.hdf5', 'r')
dset = f['coords']
dset

<HDF5 dataset "coords": shape (4, 2), type "<f4">

In [18]:
print(dset)

<HDF5 dataset "coords": shape (4, 2), type "<f4">


In [21]:
last_points = dset[:]

In [22]:
last_points

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [24]:
points = torch.tensor(dset[:])
points
f.close()

In [29]:
points_GPU_0 = torch.tensor([[4.0, 1.0], [2.0, 4.0]], device='mps:0')

In [30]:
points_GPU_5 = torch.tensor([[4.0, 1.0], [2.0, 4.0]], device='mps:5')

In [31]:
points_GPU_0 + points_GPU_5

tensor([[8., 2.],
        [4., 8.]], device='mps:0')